
name: coverage

on:
  push:
    branches: [ main , release/** , develop ]
  pull_request:
    branches: [ main , release/** , develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: install yarn    
      run: npm install yarn -g

    - name: install packages
      run: yarn install

    - name: run test suite
      run: yarn test:ci

    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with: 
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage/lcov.info
        path_to_write_report: ./coverage/codecov_report.txt
      
