# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Coverage

on:
  push:
    branches: [ main , release/** , develop ]
  pull_request:
    branches: [ main , release/** , develop ]

jobs:
  build:

    runs-on: ubuntu-latest

steps:
- uses: actions/checkout@master
- uses: codecov/codecov-action@v2
  with:
    token: ${{ secrets.CODECOV_TOKEN }}
    files: ./coverage1.xml,./coverage2.xml
    flags: unittests
    name: codecov-umbrella
    fail_ci_if_error: true
    verbose: true
- run: curl -Os https://uploader.codecov.io/latest/linux/codecov
- run: chmod +x codecov 
- run: ./codecov 