name: deploy-client

on:
  push:
    branches: [ main , release/** , develop ]
  pull_request:
    branches: [ main , release/** , develop ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: heroku git:remote -a board-game-companion-app
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          dontuseforce: false