name: deploy-client

on:
  push:
    branches: [ main , release/** , develop ]
  pull_request:
    branches: [ main , release/** , develop ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm install yarn -g
    - run: yarn install
    - run: chmod 777 tools/scripts/deploy-client.sh
    - run: yarn run deploy