name: deploy-client

on:
  push:
    branches: [ main , release/** , develop ]
  pull_request:
    branches: [ main , release/** , develop ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: yarn run deploy