name: deploy-api

on:
  push:
    branches: [ main , release/** , develop ]
  pull_request:
    branches: [ main , release/** , develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: behe/heroku-build@v1.1
        with:
          app-name: "board-game-companion-app"
          api-key: "${{secrets.HEROKU_API_KEY}}"
          path: "optional-path-of-build-to-deploy"