
name: Tests

on:
  push:
    branches: [ main , release/** , develop ]
  pull_request:
    branches: [ main , release/** , develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - run: npm install yarn -g
    - run: yarn install
    - run: yarn run test-all --unhandled-rejections=none